name: 'Next version number generator'
description: 'GithubAction for generating next version number based on the git log and message patterns'
inputs:
  major-pattern:
    description: 'Regex pattern for detecting major number bum up'
    required: false
  minor-pattern:
    description: 'Regex pattern for detecting minor number bum up'
    required: false
  patch-pattern:
    description: 'Regex pattern for detecting patch number bum up'
    required: false
  last-tag-pattern:
    description: 'Patter for matching last version tag'
    required: false
  output-to-env-variable:
    description: 'The environment variable to store the result'
    required: false
outputs:
  nextVersion: 
    description: 'The next version'
runs:
  using: 'node12'
  main: 'dist/index.js'