on: [push]

jobs:
  test_vs_publisher:
    runs-on: windows-latest
    name: A job to test VSPublisher
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test Publisher
      uses: ./
      with:
        major-pattern: 'BREAKING CHANGES:'
        minor-pattern: 'Feature:'
        minor-pattern: '.*'
        output-to-env-variable: 'VersionPrefix'